# Generated by Django 3.2.10 on 2022-08-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('choiceA', models.CharField(max_length=200, null=True)),
                ('choiceB', models.CharField(max_length=200, null=True)),
                ('choiceC', models.CharField(max_length=200, null=True)),
                ('choiceD', models.CharField(max_length=200, null=True)),
                ('correct', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
