# Generated by Django 3.2.10 on 2022-08-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_lead_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='email',
        ),
        migrations.AddField(
            model_name='category',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
