# Generated by Django 3.2.10 on 2022-08-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20220819_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='question',
        ),
    ]
