# Generated by Django 3.2.10 on 2022-08-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_delete_question'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
