# Generated by Django 3.2.10 on 2022-09-10 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20220910_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollow',
            name='userid',
        ),
        migrations.AddField(
            model_name='userfollow',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userfollows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='following',
            field=models.IntegerField(null=True),
        ),
    ]
